---
deployment:
  tasks:
    - export DEPLOY_PATH='/home/tjikkost/smpx-storybook.tjikko-studio.a2hosted.com'
    - source /home/tjikkost/nodevenv/smpx-storybook.tjikko-studio.a2hosted.com/14/bin/activate && cd $DEPLOY_PATH
    - git pull
    - npm install
    - npm run build
    - npm run build:storybook
    - cloudlinux-selector restart --json --interpreter nodejs --app-root $DEPLOY_PATH
