name: Deploy the tjikko-studio/components library
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install'
        run: npm ci
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Build'
        run: |
          ./node_modules/.bin/postcss --version
          npm run build
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Build Storybook'
        run: npm run build:storybook
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Run tests'
        run: npm test
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install'
        run: npm ci
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Build'
        run: npm run build
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Publish to npm'
        run: npm publish
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-storybook:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Add production remote'
        run: git remote add production ssh://tjikkost@tjikko-studio.a2hosted.com:7822/home/tjikkost/repositories/components

      - name: 'Push to production remote'
        run: git push production main
