name: Deploy the tjikko-studio/components library
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install'
        run: npm ci

      - name: 'Build'
        run: |
          ./node_modules/.bin/postcss --version
          npm run build

      - name: 'Build Storybook'
        run: npm run build:storybook

      - name: 'Run tests'
        run: npm test

  npm-publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install'
        run: npm ci

      - name: 'Build'
        run: npm run build

      - name: 'Publish to npm'
        run: npm publish
