name: Deploy Storybook to A2
on:
  release:
    types: [published]
jobs:
  deploy-storybook:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Add production remote'
        run: git remote add production ssh://tjikkost@tjikko-studio.a2hosted.com:7822/home/tjikkost/repositories/SMPX-Backend

      - name: 'Push to production remote'
        run: git push production
